#!/bin/sh

EMC_BIN_DIR=/home/emc2/bin
EMC_SCRIPT_DIR=/home/emc2/scripts
if [ -x $EMC_BIN_DIR/emc ]; then
    EMC=$EMC_BIN_DIR/emc
else
    EMC=$EMC_SCRIPT_DIR/emc
fi

cat <<EOF
[Desktop Entry]
Name=$2
Exec=$EMC $1
Type=Application
Comment=$3
Icon=/etc/emc2/emc2icon.png
EOF
